### ISSUE TITLE
Missing list of downloadable versions

### ISSUE THREAD

**Issue by eruvanos** [pyscript/docs#20]
While some examples feature the location of download location for specific versions, it would be great to have a list for old versions. Build artefact attached to GH releases would be enough.

**Comment by JeffersGlass** [comment]
Not that we shouldn't document this somewhere official, but the list of PyScript releases is to date is:

 - `https://pyscript.net/releases/2022.05.1/pyscript.js` (synonym for `https://pyscript.net/alpha/pyscript.js`)
 - `https://pyscript.net/releases/2022.06.1/pyscript.js`
 - `https://pyscript.net/releases/2022.09.1/pyscript.js`
 - `https://pyscript.net/releases/2022.12.1/pyscript.js`
 - `https://pyscript.net/releases/2023.03.1/pyscript.js`
 - `https://pyscript.net/releases/2023.05.1/pyscript.js`

And the upcoming release will be at `https://pyscript.net/releases/2023.09.1/core.js` when it comes out. **Note the file is now core.js**. Currently, you can see the release candidate at `https://pyscript.net/snapshots/2023.09.1.RC1/core.js`.

Tangentially related, if you (or someone who finds this later) are including those as sources on your page:
  - All releases up and including to 2023.05.1 should be used via `<script defer src="URL">`
  - All releases after 2023.09.1 should be used via `<script type="module" src="URL">`

**Comment by GoToLoop** [comment]
I'm really frustrated link for latest version is being dropped: 😭 
https://PyScript.net/latest/core.js

Please, keep it! It's super useful for demos! 🔧

**Comment by WebReflection** [comment]
@GoToLoop we publish unstable (canary channel) on NPM so you can use latest (with all its possibly breaking changs when these happen) via:

  * JS via https://cdn.jsdelivr.net/npm/@pyscript/core/dist/core.js
  * CSS via https://cdn.jsdelivr.net/npm/@pyscript/core/dist/core.css

We don't get to control *when* these will point at the very latest but that's the edge equivalent of previous `latest`.

I am closing this as I think @JeffersGlass already answered but we also list all older docs in the current site by clicking top left icon where one can pick any number.

**Comment by GoToLoop** [comment]
This is my workaround for latest PyScript if n1's interested:

* https://Unpkg.com/@pyscript/core:
`<script type=module src=//Unpkg.com/@pyscript/core></script>`

* https://Unpkg.com/@pyscript/core/dist/core.css:
`<link rel=stylesheet href=//Unpkg.com/@pyscript/core/dist/core.css>`

**Comment by WebReflection** [comment]
@GoToLoop I strongly sugest you to stop doing that as `unpkg` doesn't provide the right headers needed to bootstrap *PyScript* in a *worker* ... please use the suggested links as those are safe and working by all means:

  * JS via https://cdn.jsdelivr.net/npm/@pyscript/core/dist/core.js
  * CSS via https://cdn.jsdelivr.net/npm/@pyscript/core/dist/core.css

*unpkg* is in maintenance mode, **jsdelivr** is there to stay.

**Comment by GoToLoop** [comment]
> ...as unpkg doesn't provide the right headers needed to bootstrap PyScript in a worker...

Indeed, I've never dealt w/ workers. But for regular usage, http://Unpkg.com works for me.

> unpkg is in maintenance mode, jsdelivr is there to stay.

You mean, Unpkg is closing?!

Anyways, these are the corresponding links using https://JSDelivr.com instead:

* https://cdn.JSDelivr.net/npm/@pyscript/core:
`<script type=module src=//cdn.JSDelivr.net/npm/@pyscript/core></script>`

* https://cdn.JSDelivr.net/npm/@pyscript/core/dist/core.css:
`<link rel=stylesheet href=//cdn.JSDelivr.net/npm/@pyscript/core/dist/core.css>`

Although it's much more verbose than Unpkg...

**Comment by WebReflection** [comment]
as this is a *copy-paste* operation and as gzip, brotli, or deflate works very well with repeated same content (i.e. the whole CDN prefix) I don't think the verbosity is a great argument but fair enough ... although please do use the links I have provided for latest, don't shortcut the redirect because we have relative paths that might fail if the CDN does too smart things ... otherwise you can just go with `https://esm.run/@pyscript/core` and call it a day if that even works.
