### ISSUE TITLE
Embedded Demo Not Working?

### ISSUE THREAD

**Issue by JeffersGlass** [pyscript/docs#27]
![image](https://github.com/pyscript/docs/assets/1931111/0c16be45-15e1-4eac-93a5-c29a00615b33)

This is on the RC2 docs release.

On Chromium version 117.0.5938.92 (Official Build) snap (64-bit)
Ubuntu 22.04.1 LTS

**Comment by WebReflection** [comment]
AFAIK this is no longer an issue.
