### ISSUE TITLE
Is it possible to close a terminal after the desired work is complete?

### ISSUE THREAD

**Issue by cclauss** [pyscript/docs#69]
https://pyscript.github.io/docs/2024.2.1/user-guide/terminal does not explain how to close a terminal to free up space on the web page.

Use case:
* I want users to see that I have run `pytest` on the code before they rely on it.  However, once the tests have run I would like to close the terminal so that users have more space to do their work.  Alternatively, could I at least minimize the terminal?
```html
    <script type="py" config="./pyscript.toml" terminal worker>
        import code, pytest, time
        pytest.main()  # Run all pytests and give the user a few seconds to read the results.
        time.sleep(3)  # Should we consider calling async.sleep() instead?
        print("-" * 20)  # When the pytests are complete, is it possible to close the terminal?
        # exit()  # Does not work
        # sys.exit()  # Does not work
        # If I cannot close the terminal, can I minimize it?
        # Last resort...
        code.interact()  # Convert the terminal into a Python REPL.
    </script>
```

**Comment by WebReflection** [comment]
you can always give that terminal an id, use `from pyscript import document` and whenever you want `document.getElementById("your-terminal").terminal.dispose()` https://xtermjs.org/docs/api/terminal/classes/terminal/#dispose

although I haven't tried myself but it's part of the XTerm API

**Comment by cclauss** [comment]
Works like a champ!  Thanks much.
```python
    <script id="pytest_terminal" type="py" config="./pyscript.toml" terminal worker>
        import pyscript, pytest, time
        print("Pytest runs on a background worker at startup and then disappears.")
        pytest.main()  # Run all pytests and give the user a few seconds to read the results.
        time.sleep(3)  # Should we consider calling async.sleep() instead?
        pyscript.document.getElementById("pytest_terminal").terminal.dispose()
        # pyweb.pydom["#pytest_terminal"][0]._js.terminal.dispose()
    </script>
```

Using a Worker was a performance consideration because I wanted the run the tests without unnecessarily slowing down app setup.

Should we use [`time.sleep()`](https://docs.python.org/3/library/time.html#time.sleep) or [`async.sleep()`](https://docs.python.org/3/library/asyncio-task.html#sleeping) in Workers?  I guess that `time.sleep()` should be OK.

**Comment by WebReflection** [comment]
in workers `time.sleep()` won't block the main so it should be OK ... keep using workers if it helps, mine was rather an extra hint around the specific use case, but of course when workers are possible/available (due headers constraints) I would always suggest workers VS main thread 👍
