### ISSUE TITLE
[DocsWeek] F.A.Q. & Common Errors

### ISSUE THREAD

**Issue by WebReflection** [pyscript/docs#81]
There are a lot of repeated questions in Discord about the very same error over and over ... CDN issues, SharedArrayBuffer and COOP related issues, local vFS VS Server files hosted here and there ... these scenario require a dedicatewd space to me as it feels weird to need to always re-answer the same questions for people that even read the docs but couldn't figure out what's going on.

**Comment by WebReflection** [comment]
I feel like this issue could be more suitable as **F.A.Q.** section where we tackle a bounce of common problems or solutions with examples and stuff ... this would also cover the other issue around file uploads as it's part of the project's F.A.Q. ... imho ... @ntoll what do you think?

**Comment by ntoll** [comment]
FAQ++ :rocket:
